Models/Client.cs
using Bank.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace Bank.Models
{
    public class Client
    {
        public int ID { get; set; }
        [Column(TypeName = "VARCHAR")]
        [StringLength(10, ErrorMessage = "Invalid EGN")]
        public string EGN { get; set; }
        public string NAME { get; set; }
        public string address { get; set; }
        [Column(TypeName = "VARCHAR")]
        [StringLength(13, ErrorMessage = "Invalid phone number")]
        public string PN { get; set; }
        public virtual AccountUser user { get; set; }
        public string UserId { get; set; }

        public Client() { }
    }
}

Controllers/CashierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bank.Data;
using Bank.Models;
using Bank.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace Bank.Controllers
{
    public class CashierController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AccountUser> _userManager;

        public CashierController(ApplicationDbContext context, UserManager<AccountUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Cashier
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult ViewAll(string bankAccIDSpecial)
        {
            if (bankAccIDSpecial != null)
            { 
                ViewData["bankAccIDSpecial"] = bankAccIDSpecial; 
            }
            else
            {
                ViewData["BankAccId"] = new SelectList(_context.BankAccount, "ID", "ID");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ViewAll(string bankAccID, DateTime? transTimeFrom, DateTime? transTimeTo)
        {

            if (bankAccID != null)
            {
                IQueryable<Transaction> applicationDbContext;
                if (transTimeFrom != null) {
                    if (transTimeTo != null) {
                        applicationDbContext = _context.Transaction.Where(v => v.BankAccId == int.Parse(bankAccID) && v.DATE >= transTimeFrom && v.DATE <= transTimeTo);
                        return View(await applicationDbContext.ToListAsync());
                    }
                    applicationDbContext = _context.Transaction.Where(v => v.BankAccId == int.Parse(bankAccID) && v.DATE >= transTimeFrom );
                    return View(await applicationDbContext.ToListAsync());
                }

                applicationDbContext = _context.Transaction.Where(v => v.BankAccId == int.Parse(bankAccID));
                return View(await applicationDbContext.ToListAsync());
            }
            else {
                ViewData["error"] = "Some of the fields are empty!";
                ViewData["BankAccId"] = new SelectList(_context.BankAccount, "ID", "ID");
                return View();
            }
           
        }

        // GET: Cashier/Create
        public IActionResult Create()
        {
            var user = _userManager.GetUserAsync(User).Result;
            ViewData["EmployeeId"] = _context.Employee.Where(v => v.UserId == user.Id).FirstOrDefault().ID;
            ViewData["BankAccId"] = new SelectList(_context.BankAccount, "ID", "ID");
            ViewData["TransCatId"] = new SelectList(_context.TransactionCategory, "ID", "NAME");
            return View();
        }

        // POST: Cashier/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransCatId,SUM,EmployeeId,BankAccId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                transaction.bankAccount = _context.BankAccount.Where(v => v.ID == transaction.BankAccId).FirstOrDefault();
                transaction.employee = _context.Employee.Where(v => v.ID == transaction.EmployeeId).FirstOrDefault();
                transaction.transactionCategory = _context.TransactionCategory.Where(v => v.ID == transaction.TransCatId).FirstOrDefault();
                transaction.DATE = dt;
                _context.Add(transaction);
                float sum = transaction.SUM * transaction.transactionCategory.COEF;//_context.TransactionCategory.Where(v => v.ID == transaction.TransCatId).FirstOrDefault().COEF;
                _context.BankAccount.Where(v => v.ID == transaction.BankAccId).FirstOrDefault().BALANCE += sum;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ViewAll));
            }
            var user = _userManager.GetUserAsync(User).Result;
            ViewData["EmployeeId"] = _context.Employee.Where(v => v.UserId == user.Id).FirstOrDefault().ID;
            ViewData["BankAccId"] = new SelectList(_context.BankAccount, "ID", "ID", transaction.EmployeeId);
            ViewData["TransCatId"] = new SelectList(_context.TransactionCategory, "ID", "NAME");
            return View(transaction);
        }

    }
}

Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bank.Data;
using Bank.Models;
using Bank.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace Bank.Controllers
{
    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AccountUser> _userManager;

        public ClientController(ApplicationDbContext context, UserManager<AccountUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Client
        public IActionResult Index()
        {
            var user = _userManager.GetUserAsync(User).Result;

            var currentClient = _context.Client.Where(p => p.UserId == user.Id).FirstOrDefault();

            var clientBankAcc = _context.BankAccount.Where(c => c.ClientId == currentClient.ID).ToList();

            List<BankAccount> legitBankAccounts = new List<BankAccount>();

            foreach (BankAccount item in clientBankAcc)
            {
                var temp = item;
                temp.currency = _context.Currency.Where(v => v.ID == item.CurrencyId).FirstOrDefault();
                temp.acctype = _context.AccountType.Where(v => v.ID == item.AccTypeId).FirstOrDefault();
                legitBankAccounts.Add(temp);

            }

            return View(legitBankAccounts);
        }

        // GET: Client/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .Include(c => c.user)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Client/Create
        public IActionResult Create(string id)
        {
            ViewData["UserId"] = id;
            ViewData["CurrencyId"] = new SelectList(_context.Currency, "ID", "ID");
            ViewData["AccTypeId"] = new SelectList(_context.AccountType, "ID", "ID");
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EGN,NAME,address,PN,UserId")] Client client)
        {
            int[] tegla  = new int [9] { 2, 4, 8, 5, 10, 9, 7, 3, 6 };
            int lastnum = 0;
            for(int i = 0; i < 9; i++)
            {
                lastnum += int.Parse(client.EGN.Substring(i, 1)) * tegla[i];
            }
            lastnum = lastnum % 11;
            if (lastnum == 10) { lastnum = 0; }
            if (lastnum != int.Parse(client.EGN.Substring(9, 1))){
                ViewData["UserId"] = client.UserId;
                ViewData["error"] = "EGN was input incorrectly!";
                return View(client);
            }

            if (client.PN.Substring(0, 1) != "+") {
                ViewData["UserId"] = client.UserId;
                ViewData["error"] = "Phone number is incorrect!";
                return View(client);
            }

            if (ModelState.IsValid)
            {
                _context.Add(client); //zapisva v bazata danni
                await _context.SaveChangesAsync(); //zapisva v context
                //return RedirectToAction(nameof(Index)); //otiva v stranica index na klienta
                return RedirectToAction("CreateBankAcc", "Banker", new { clientID = client.ID });
            }
            ViewData["UserId"] = client.UserId;
            ViewData["error"] = "Client data incorrect!";
            return View(client);
        }


        // GET: Client/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .Include(c => c.user)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);

            var clientBankAcc = _context.BankAccount.Where(c => c.ClientId == client.ID).ToList();

            foreach (BankAccount item in clientBankAcc)
            {
                var trans = _context.Transaction.Where(c => c.BankAccId == item.ID).ToList();
                foreach (Transaction elem in trans)
                {
                    _context.Transaction.Remove(elem);
                }
                    _context.BankAccount.Remove(item);
            }
            _context.Client.Remove(client);
            var user = await _userManager.FindByIdAsync(client.UserId);

            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Banker");
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.ID == id);
        }
    }
}

Views/Client/Create.cshtml
@model Bank.Models.Client

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Client</h4>
<hr />
@if (ViewData["error"] != null)
{
    <div class="alert-danger">
        <p name="empID" class="control-label">@ViewData["error"]</p>
    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EGN" class="control-label">EGN</label>
                <input asp-for="EGN" class="form-control" />
                <span asp-validation-for="EGN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NAME" class="control-label">Name</label>
                <input asp-for="NAME" class="form-control" />
                <span asp-validation-for="NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label">Adress</label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PN" class="control-label">Phone number</label>
                <input asp-for="PN" class="form-control" />
                <span asp-validation-for="PN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label">
                    <input asp-for="UserId" class="form-control" type="hidden" value="@ViewData["UserId"]" />
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Client/Delete.cshtml
@model Bank.Models.Client

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            EGN
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EGN)
        </dd>
        <dt class = "col-sm-2">
            Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class = "col-sm-2">
            Adress
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            Phone number
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PN)
        </dd>
        <dt class = "col-sm-2">
            User ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.user.Id)
        </dd >
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Client/Details.cshtml
@model Bank.Models.Client

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            EGN
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EGN)
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class="col-sm-2">
            Address
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class="col-sm-2">
            Phone number
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PN)
        </dd>
        <dt class="col-sm-2">
            User ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.user.Id)
        </dd>
    </dl>
</div>

Views/Client/Index.cshtml
@model IEnumerable<Bank.Models.BankAccount>

@{
    ViewData["Title"] = "Index";
}

<style>

    body {
        /* tuk se smenia fona na stranicata na klienta */ background-color: #61a5c2;
    }

    .clientButton {
        font-family: 'Roboto', sans-serif;
        background: none;
        color: #014f86;
        border: 2px solid;
        font-size: 1em;
        transition: color 0.25s, border-color 0.25s, box-shadow 0.25s,transform 0.25s;
    }

    .clientButton:hover {
        border-color: #90e0ef;
        color: #fff1e6;
        box-shadow: 0 0.5em 0.5em -0.4em #fff1e6;
        transform: translateY(-0.25em);
        cursor: pointer;
    }

</style>


<h1>Your Bank Accounts:</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Bank Account ID
            </th>
            <th>
                Currency
            </th>
            <th>
                Balance
            </th>
            <th>
                Account Type
            </th>
            <th>
                Transaction History
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
         {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.currency.FULL_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BALANCE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.acctype.NAME)
                </td>
                <td>
                    <form asp-action="ViewAll" asp-controller="Cashier" method="get">
                        <input type="hidden" name="bankAccIDSpecial" id="bankAccIDSpecial" value="@item.ID.ToString()">
                        <button class="clientButton" type="submit">View transactions</button>
                    </form>
                </td>
            </tr>
         }
    </tbody>
</table>